name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
            java-version: 17
            distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Lint Check
        run: ./gradlew -xlint

      - name: Run Tests
        run: ./gradlew test

      - name: Upload a Build Artifact (APK)
        uses: actions/upload-artifact@v4
        with:
            name: app
            path: app/build/outputs/apk/debug/app-debug.apk